### ISSUE TITLE
Canary user secret and missing KMS key

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#613]
### Describe the bug

Get `AttributeError: 'SecretsManagerStack' object has no attribute 'external_id_key'` in CodeBuild CDK Synth stage after upgrading to V1.6:

<img width="776" alt="image" src="https://github.com/awslabs/aws-dataall/assets/71252798/bcd24b81-2591-4cac-a471-fc3310a3a5ef">

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

na

### Python version

na

### AWS data.all version

v.1.6.1

**Comment by dlpzx** [comment]
Solved
